// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteContasPagar.Dal;

namespace TesteContasPagar.Migrations
{
    [DbContext(typeof(ContasPagarContext))]
    [Migration("20201114154326_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TesteContasPagar.Models.ContaPagar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiasAtraso")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegraAtrasoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCorrigido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RegraAtrasoId");

                    b.ToTable("ContaPagar");
                });

            modelBuilder.Entity("TesteContasPagar.Models.RegraAtraso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Descricao")
                        .HasColumnType("int");

                    b.Property<int>("DiasAtraso")
                        .HasColumnType("int");

                    b.Property<decimal>("JurosDia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Multa")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("RegraAtraso");
                });

            modelBuilder.Entity("TesteContasPagar.Models.ContaPagar", b =>
                {
                    b.HasOne("TesteContasPagar.Models.RegraAtraso", "RegraAtraso")
                        .WithMany()
                        .HasForeignKey("RegraAtrasoId");

                    b.Navigation("RegraAtraso");
                });
#pragma warning restore 612, 618
        }
    }
}
